version: '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: always
    container_name: burger-statio-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: burger_station_db
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
